title: Chiwan Park
author: Chiwan Park
email: chiwanpark@hotmail.com
baseurl: ""
url: "https://chiwanpark.com"

# Collections
collections:
  posts:
    output: false
  writings:
    output: true
    permalink: /:collection/:path.html

# Build settings
plugins:
  - jekyll-feed
  - jekyll-git_metadata
  - jekyll-asciidoc
asciidoc: {}
asciidoctor:
  attributes:
    source-highlighter: highlightjs
feed:
  collections:
    writings:
      path: "/feed.xml"
    posts:
      path: "/feed-dummy.xml" # prevent create RSS feed from posts collection
sitemap: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
