= Chiwan Park
:page-layout: static
:page-permalink: /

I'm a machine learning engineer at ART (Advanced Recommendation Technology) team of link:http://www.kakaocorp.com[Kakao Corporation] where I'm building recommender systems and machine learning applications for various mobile and web services of Kakao.
Before joining Kakao ART team, I did some research on large-scale graph processing using distributed systems under guidance of link:https://datalab.snu.ac.kr/~ukang/[Prof. U Kang] at Seoul National University.
Here is my full link:http://bit.ly/chiwanpark-cv[Curriculum Vitae].

Outside of paid works, I enjoy developing various softwares. I have contributed to some open-source software projects such as link:https://flink.apache.org/[Apache Flink], and link:https://github.com/atlassian/commonmark-java[commonmark-java].
You can see my activities about open-source software in link:https://github.com/chiwanpark[Github].

== News
* **Jan. 24, 2020** - A paper, "FlexGraph: Flexible partitioning and storage for scalable graph mining" was published to PLoS ONE.
* **Aug. 30, 2019** - I gave a talk named "link:http://j.mp/chiwanpark-ifkakao2019[상품 카탈로그 자동 생성 ML 모델 소개]" at link:https://if.kakao.com[if (kakao)dev 2019].
* **Apr. 30, 2018** - I joined ART team of Kakao Corp. as a software engineer.
* **Nov. 10, 2017** - A demo paper, "PegasusN: A Scalable and Versatile Graph Mining System" was accepted to AAAI 2018.
* **Mar. 2, 2016** - I joined Data Mining Laboratory at Seoul National University as a master's student.

[.cv-list]
== Education
Master of Science in Computer Science and Engineering:: 
Mar. 2016 - Feb. 2018
Seoul National University, Seoul, Korea

+++Bachelor of Science in Earth System Sciences<br/>Bachelor of Engineering in Computer Science (double major)+++::
Mar. 2010 - Feb. 2016
Yonsei University, Seoul, Korea

[.cv-list]
== Publications
FlexGraph: Flexible partitioning and storage for scalable graph mining::
Chiwan Park, Ha-Myung Park, and U Kang.
PLoS ONE 15(1): e0227032
link:https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0227032[[paper\]] link:https://github.com/snudatalab/FlexGraph[[github\]]

PegasusN: A Scalable and Versatile Graph Mining System::
Ha-Myung Park, Chiwan Park, and U Kang.
Thirty-Second AAAI Conference on Artificial Intelligence (AAAI) 2018, New Orleans, Lousiana, USA.
(Demo Paper)
link:https://www.aaai.org/ocs/index.php/AAAI/AAAI18/paper/viewFile/16474/16451[[paper\]] link:https://datalab.snu.ac.kr/pegasusn[[homepage (code)\]]

PMV: Pre-partitioned Generalized Matrix-Vector Multiplication for Scalable Graph Mining::
Chiwan Park, Ha-Myung Park, Minji Yoon, and U Kang.
arXiv:1709.09099 [cs.DC] Sep. 2017.
link:https://arxiv.org/abs/1709.09099[[paper\]]

A Distributed Vertex Rearrangement Algorithm for Compressing and Mining Big Graphs::
Namyong Park, Chiwan Park, and U Kang
Journal of KIISE, Vol. 43, No. 10, pp. 1131-1143, 2016.
link:https://datalab.snu.ac.kr/dslashburn/dslashburn.pdf[[paper\]] link:https://datalab.snu.ac.kr/dslashburn/[[homepage (code, dataset)\]]
