= Chiwan Park
:page-layout: static
:page-permalink: /

I'm a software engineer at ART (Advanced Recommendation Technologies) team of link:http://www.kakaocorp.com[Kakao Corporation] where I'm building machine learning applications for various mobile and web services of Kakao.
Before joining Kakao ART team, I did some research on large-scale graph processing on distributed systems under guidance of link:https://datalab.snu.ac.kr/~ukang/[Prof. U Kang].
Here is my full link:http://bit.ly/chiwanpark-cv[Curriculum Vitae].

== News
* **Apr. 30, 2018** - I joined ART team at Kakao Corp. as a software engineer.
* **Nov. 10, 2017** - A demo paper, "PegasusN: A Scalable and Versatile Graph Mining System" was accepted to AAAI 2018.
* **Mar. 2, 2016** - I joined Data Mining Laboratory at Seoul National University as a master's student.
* **Feb. 26, 2016** - I gave a talk named "link:http://j.mp/d2-campus-seminar-4th-park[학교에선 알려주지 않는 오픈 소스 이야기]"
  at link:http://d2.naver.com/news/2137145[NAVER 4th D2 Campus Seminar], Korea.
* **Dec. 22, 2015** - I gave a talk named "link:http://j.mp/ossdevconf-2015-park[Introduction to Apache Flink]" at Open-source Software Developer Center Conference in Korea.

[.cv-list]
== Education
Master of Science in Computer Science and Engineering:: 
Mar. 2016 - Feb. 2018
Seoul National University, Seoul, Korea

+++Bachelor of Science in Earth System Sciences<br/>Bachelor of Engineering in Computer Science (double major)+++::
Mar. 2010 - Feb. 2016
Yonsei University, Seoul, Korea

[.cv-list]
== Publications
PegasusN: A Scalable and Versatile Graph Mining System::
Ha-Myung Park, Chiwan Park, and U Kang.
Thirty-Second AAAI Conference on Artificial Intelligence (AAAI) 2018, New Orleans, Lousiana, USA.
(Demo Paper)
link:https://datalab.snu.ac.kr/pegasusn[[homepage (code)]]

PMV: Pre-partitioned Generalized Matrix-Vector Multiplication for Scalable Graph Mining::
Chiwan Park, Ha-Myung Park, Minji Yoon, and U Kang.
arXiv:1709.09099 [cs.DC] Sep. 2017.
link:https://arxiv.org/abs/1709.09099[[paper]]

A Distributed Vertex Rearrangement Algorithm for Compressing and Mining Big Graphs::
Namyong Park, Chiwan Park, and U Kang
Journal of KIISE, Vol. 43, No. 10, pp. 1131-1143, 2016.
link:https://datalab.snu.ac.kr/dslashburn/dslashburn.pdf[[paper]] link:https://datalab.snu.ac.kr/dslashburn/[[homepage (code, dataset)]]

[.cv-list]
== Projects
Recommender System on Videos of oksusu application::
Keywords: Multi-model Recommender System, Deep Learning, Word2Vec
Jul. 2017 - Feb. 2018
SK Telecom Media IT Lab., Seoul, Korea

Development of Distributed Machine Learning Algorithms::
Keywords: Apache Spark, Distributed DBSCAN, Linear Discriminant Analysis, Incremental PCA
Apr. 2016 - Dec. 2016
SK Telecom Big Data Tech Lab., Seongnam, Korea

High Performance Big Data Analytics Platform Performance Acceleration Technologies Development::
Keywords: Apache Hadoop, Apache Spark, Distributed Graph Processing, Matrix-Vector Multiplication
Mar. 2016 - Mar. 2018
UNIST, Ulsan, Korea

[.cv-list]
== Teaching Experiences
Teaching Assistant of Basic Math for Big Data::
Big Data Institute in Seoul National University, Summer 2017

Teaching Assistant of Introduction to Data Mining::
Seoul National University, Spring 2017

Teaching Assistant of Data Structures::
Seoul National University, Fall 2016

[.cv-list]
== Extra Activities
System Administrator in SNU Data Mining Lab.::
I manage 3 web servers, 17 machines equipped Hadoop cluster, and 5 GPU-installed machines with LDAP authentication.
Mar. 2016 - Mar. 2018

Homepage Administrator of SNU Data Mining Lab.::
I manage our lab homepage built on CodeIgniter and PHP.
Mar. 2016 - Mar. 2018

Committer of Apache Flink::
I have contributed to Apache Flink, a scalable distributed data processing framework, as a committer.
Nov. 2014 - Present
